# Default values for helm-manifests.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

fullnameOverride: "user-service"

image: eubash/configurator-user-service:1.0.1

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: true
  hosts:
    - host: user.service
      paths: ["/users"]

config:
  name: configurator-user-config

secret:
  name: configurator-user-secret

externalMongodb:
  mongodbUsername: superuser
  mongodbPassword: somepass
  mongodbDatabase: mongodb
  mongodbDatabaseName: someapp
  mongodbHost: "mongo-db"
  mongodbPort: "27017"


