apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "front-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "front-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          env:
            - name: BASE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.name }}
                  key: BASE_API_URL
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5