apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-chart.fullname" . }}
  labels:
    {{- include "front-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "front-chart.selectorLabels" . | nindent 4 }}
