# Default values for helm-manifests.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

fullnameOverride: "auth-service"

image: eubash/configurator-auth-service:1.0.5

service:
  type: NodePort
  port: 8000

ingress:
  enabled: true
  hosts:
    - host: api.service
      paths: ["/login", "/signup", "/whoAmI", "/users"]

config:
  name: configurator-config

secret:
  name: configurator-secret

externalMongodb:
  mongodbUsername: superuser
  mongodbPassword: somepass
  mongodbDatabase: mongodb
  mongodbDatabaseName: someapp
  mongodbHost: "mongo-db"
  mongodbPort: "27017"


