apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  DATABASE_NAME: articulates
  DATABASE_USER: admin
  DATABASE_PASSWORD: 2PPHDtAPB7
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  DATABASE_URI: {{ printf "mongodb://%s:%s@%s:%s/%s" .Values.externalMongodb.mongodbUsername .Values.externalMongodb.mongodbPassword .Values.externalMongodb.mongodbHost .Values.externalMongodb.mongodbPort .Values.externalMongodb.mongodbDatabaseName | b64enc | quote }}
  MYSQL_DATABASE_URI: {{ printf "mysql://%s:%s@%s/%s" .Values.externalMySQLdb.dbUsername .Values.externalMySQLdb.dbPassword .Values.externalMySQLdb.dbHost .Values.externalMySQLdb.dbDatabaseName | b64enc | quote }}