apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "product-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "product-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: DATABASE_URI
            - name: MYSQL_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: MYSQL_DATABASE_URI
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              port: 3002
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 3002
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5