apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-chart.fullname" . }}
  labels:
    {{- include "product-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs:
    - 192.168.99.115
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3002
      protocol: TCP
  selector:
    {{- include "product-chart.selectorLabels" . | nindent 4 }}
