apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs:
    - 192.168.99.115
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}
